### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by hannahcmtucker** [FAC-Sixteen/farage-barrage#10]
When i run this locally i get a type error `Cannot read property 'avatar_url' of undefined` from this line 
```
    getUserData(username).then(response => setImg(response.avatar_url));

```

If you aren't sure if response will be present, it's always best to set a fallback
```
getUserData(username).then((response = {}) => setImg(response.avatar_url));
```

**Comment by hannahcmtucker** [comment]
ah this was caused by the missing access token, but still good practice :)

**Comment by bobbysebolao** [comment]
Yes, we ran into the same issue, until we realised that our access token was invalid!
