### ISSUE TITLE
Error response

### ISSUE THREAD

**Issue by hannahcmtucker** [FAC-Sixteen/farage-barrage#17]
At the moment, if your API call fails, you simply return
```
if (response.status !== 200) {
    console.log(`Error with the request! ${response.status}`);
    return;
  }
```
And in your UI you see "Loading..." which never updates.

How about if you had some error state in you component, 
```
const [error, setError] = React.useState(null);
```

And from the api you returned something to indicate that an error had happened
```
if (response.status !== 200) {
    console.log(`Error with the request! ${response.status}`);
    return { errorResponse: `Error with the request! ${response.status}`};
  }
```
And used it to update your component state, so either you `setImg` or `setError`
```
getUserData(username).then(({ errorResponse, avatar_url }) =>
      errorResponse ? setError(errorResponse) : setImg(avatar_url)
    );
```
So that the message "loading..." doesn't appear if something went wrong
```
if (!img && !error) {
    return <p>Loading...</p>;
  }

**Comment by hannahcmtucker** [comment]
might be a stretch goal :)

**Comment by hrmstockdale** [comment]
@hannahcmtucker This is super detailed and much appreciated. Conditional rendering to handle and display errors is v good idea. Thank you Hannah
