### ISSUE TITLE
Confusing argument names

### ISSUE THREAD

**Issue by oliverjam** [FAC-Sixteen/farage-barrage#19]
https://github.com/FAC-Sixteen/farage-barrage/blob/12c80ef43c0f02d54d56a29b554167866a617b5b/src/App.js#L9-L11

Here you've named the argument to your click handler `prevPoints`. You've also named the argument to your state update function `prevPoints`. Since the second one takes precedence you're never actually using the first. Also since it's an event handler it's going to get called with the click event. It's a bit misleading to name that anything other than `event` imo. If you're not using it then you may as well just start the handler with `() =>`

**Comment by hannahcmtucker** [comment]
I would also say that `twoFuncs` is slightly unusual :) maybe either something descriptive like `updateScoreSetPosition` or something like `onClickHandler`

Naming is hard!
